apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mariadb
          imagePullPolicy: Never
          name: db
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
          ports:
            - containerPort: 3306
              name: db
